In [97]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [98]:
data=pd.read_csv('/content/Iris.csv')
#Matrix=data.values
data=data[data['Species'].isin(['Iris-versicolor','Iris-virginica'])]#gets the required rows
data.head()
data['Species']=data['Species'].map({'Iris-versicolor':0,'Iris-virginica':1})
#data
X_train=data.sample(n=80,replace=False,random_state=1) #extracts random 80 rows from the dataset
Y_train=data.sample(n=80,replace=False,random_state=1)
X_test=data.drop(X_train.index)  #drops the rows
Y_test=data.drop(Y_train.index)  #drops the rows
X_train.drop(columns=['Id','Species'],inplace=True)  #I get the feature dataset
X_test.drop(columns=['Id','Species'],inplace=True)
Y_train.drop(columns=['Id','SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm'],inplace=True)#I get the species
Y_test.drop(columns=['Id','SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm'],inplace=True)
X_train=X_train.values  #feature matrix
X_test=X_test.values


In [99]:
ones_column=np.ones((X_train.shape[0],1))
one_column=np.ones((X_test.shape[0],1))
X_0=np.hstack((ones_column,X_train))
X_1=np.hstack((one_column,X_test))
X_0


array([[1. , 7.4, 2.8, 6.1, 1.9],
       [1. , 6.1, 2.6, 5.6, 1.4],
       [1. , 6. , 2.7, 5.1, 1.6],
       [1. , 7.9, 3.8, 6.4, 2. ],
       [1. , 6.8, 3.2, 5.9, 2.3],
       [1. , 5.8, 2.7, 4.1, 1. ],
       [1. , 6.7, 3.1, 4.7, 1.5],
       [1. , 6.4, 2.8, 5.6, 2.2],
       [1. , 6. , 2.2, 5. , 1.5],
       [1. , 6.4, 3.2, 5.3, 2.3],
       [1. , 5.8, 2.7, 5.1, 1.9],
       [1. , 5.5, 2.5, 4. , 1.3],
       [1. , 4.9, 2.5, 4.5, 1.7],
       [1. , 7.1, 3. , 5.9, 2.1],
       [1. , 5.8, 2.7, 5.1, 1.9],
       [1. , 5.8, 2.7, 3.9, 1.2],
       [1. , 5.5, 2.4, 3.7, 1. ],
       [1. , 5.6, 2.7, 4.2, 1.3],
       [1. , 6.4, 2.8, 5.6, 2.1],
       [1. , 5. , 2. , 3.5, 1. ],
       [1. , 6.9, 3.1, 4.9, 1.5],
       [1. , 6.3, 2.7, 4.9, 1.8],
       [1. , 6.5, 3. , 5.2, 2. ],
       [1. , 6.8, 3. , 5.5, 2.1],
       [1. , 5.6, 2.5, 3.9, 1.1],
       [1. , 6. , 3.4, 4.5, 1.6],
       [1. , 6.7, 3.3, 5.7, 2.5],
       [1. , 6.7, 3. , 5. , 1.7],
       [1. , 5.7, 2.9, 4.2, 1.3],
       [1. , 5

In [100]:
Y_0=Y_train.values
Y_1=Y_test.values
Y_1

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [101]:
#print(Y_train.shape)
weights=np.zeros((X_0.shape[1],1))
weights

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [102]:
def sigmoid(x):
  return 1/(1+np.exp(-x))


In [103]:
def grad(l,iterations,X,Y,weights):
  for i in range(iterations):
    linear_predictions=np.dot(X,weights)
    y_p=sigmoid(linear_predictions)
    gradient=(1/80)*np.dot(X.T,(y_p-Y))
    weights=weights-l*gradient
  return weights



In [104]:
weights=grad(0.01,10000,X_0,Y_0,weights)
weights

array([[-1.43242143],
       [-2.48267758],
       [-1.80831401],
       [ 3.29157212],
       [ 3.73305058]])

In [105]:
def accuracy(y_true,y_pred):  #function for accuracy
  accuracy=np.sum(y_true==y_pred)/len(y_true)
  return accuracy

In [106]:
#sigmoid(np.dot(X_1,weights))
Predictions=(sigmoid(np.dot(X_1,weights))>=0.5).astype(int)
print(accuracy(Y_1,Predictions)*100)

95.0
