In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [518]:
X=pd.read_csv('/content/iris.csv')
X

Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0            1           7.0          3.2           4.7          1.4        1
1            2           6.4          3.2           4.5          1.5        1
2            3           6.9          3.1           4.9          1.5        1
3            4           5.5          2.3           4.0          1.3        1
4            5           6.5          2.8           4.6          1.5        1
..         ...           ...          ...           ...          ...      ...
95          96           6.7          3.0           5.2          2.3        0
96          97           6.3          2.5           5.0          1.9        0
97          98           6.5          3.0           5.2          2.0        0
98          99           6.2          3.4           5.4          2.3        0
99         100           5.9          3.0           5.1          1.8        0

[100 rows x 6 columns]

In [526]:
df
df.rename(columns={'Unnamed: 0': 'id'}, inplace=True)
X=df
X

id  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
0     1           7.0          3.2           4.7          1.4        1
1     2           6.4          3.2           4.5          1.5        1
2     3           6.9          3.1           4.9          1.5        1
3     4           5.5          2.3           4.0          1.3        1
4     5           6.5          2.8           4.6          1.5        1
..  ...           ...          ...           ...          ...      ...
95   96           6.7          3.0           5.2          2.3        0
96   97           6.3          2.5           5.0          1.9        0
97   98           6.5          3.0           5.2          2.0        0
98   99           6.2          3.4           5.4          2.3        0
99  100           5.9          3.0           5.1          1.8        0

[100 rows x 6 columns]

In [534]:
X_train=X.sample(n=80,random_state=1)
Y_train=X.sample(n=80,random_state=1)
columns_X = ['id','Species']
column_Y=['id','Sepal.Length','Sepal.Width','Petal.Length','Petal.Width']

# Remove the specified columns
X_train = X_train.drop(columns=columns_X)
Y_train =Y_train.drop(columns=column_Y)
X_test=X.drop(X_train.index)
Y_test=X.drop(Y_train.index)
columns_X = ['id','Species']
column_Y=['id','Sepal.Length','Sepal.Width','Petal.Length','Petal.Width']

# Remove the specified columns
X_test = X_test.drop(columns=columns_X)
Y_test=Y_test.drop(columns=column_Y)


In [535]:
Y_train=Y_train.values
Y_test=Y_test.values
ones_column=np.ones((X_train.shape[0],1))
one_column=np.ones((X_test.shape[0],1))
X_train=np.hstack((ones_column,X_train))
X_test=np.hstack((one_column,X_test))
X_train

array([[1. , 7.4, 2.8, 6.1, 1.9],
       [1. , 6.1, 2.6, 5.6, 1.4],
       [1. , 6. , 2.7, 5.1, 1.6],
       [1. , 7.9, 3.8, 6.4, 2. ],
       [1. , 6.8, 3.2, 5.9, 2.3],
       [1. , 5.8, 2.7, 4.1, 1. ],
       [1. , 6.7, 3.1, 4.7, 1.5],
       [1. , 6.4, 2.8, 5.6, 2.2],
       [1. , 6. , 2.2, 5. , 1.5],
       [1. , 6.4, 3.2, 5.3, 2.3],
       [1. , 5.8, 2.7, 5.1, 1.9],
       [1. , 5.5, 2.5, 4. , 1.3],
       [1. , 4.9, 2.5, 4.5, 1.7],
       [1. , 7.1, 3. , 5.9, 2.1],
       [1. , 5.8, 2.7, 5.1, 1.9],
       [1. , 5.8, 2.7, 3.9, 1.2],
       [1. , 5.5, 2.4, 3.7, 1. ],
       [1. , 5.6, 2.7, 4.2, 1.3],
       [1. , 6.4, 2.8, 5.6, 2.1],
       [1. , 5. , 2. , 3.5, 1. ],
       [1. , 6.9, 3.1, 4.9, 1.5],
       [1. , 6.3, 2.7, 4.9, 1.8],
       [1. , 6.5, 3. , 5.2, 2. ],
       [1. , 6.8, 3. , 5.5, 2.1],
       [1. , 5.6, 2.5, 3.9, 1.1],
       [1. , 6. , 3.4, 4.5, 1.6],
       [1. , 6.7, 3.3, 5.7, 2.5],
       [1. , 6.7, 3. , 5. , 1.7],
       [1. , 5.7, 2.9, 4.2, 1.3],
       [1. , 5

In [ ]:
# w=np.random.rand(X_train.shape[1],1)

# b=np.zeros((X_train.shape[0],1))
# print(X_train.shape)
# c=np.dot(X_train,w)+b
# print()

In [563]:
def sigmoid(z):
  return 1/(1+np.exp(-z))

In [564]:
w=np.zeros((X_train.shape[1],1))

In [565]:
def logistic_reg(X,Y,epoch,rate,n,w):
  #w=np.zeros((X.shape[1],1))
  #b=np.zeros((X_t.shape[0],1))
  for i in range(epoch):
    z=np.dot(X,w)
    y_pred=sigmoid(z)
    dw =(-1/n) * np.dot(X.T,(Y-y_pred))
    #db=(1/n) * np.sum(Y-y_pred)
    w=(w)-(rate)*(dw)
    #b=b-rate*db
  return w

In [566]:
def prediction(X_t,w):
   z=np.dot(X_t,w)
   y_pred=sigmoid(z)
   ans=[0 if y<=0.5 else 1 for y in y_pred]
   return ans

In [573]:
#np.zeros((X.shape[1],1))
weights=logistic_reg(X_train,Y_train,100000,0.001,80,w)
ans=prediction(X_test,weights)
print(ans)


[[ 1.43237985]
 [ 2.48257424]
 [ 1.80824639]
 [-3.29143599]
 [-3.73292404]]
[1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0]


In [ ]:
def accuracy (y_pred, y_test):
  return np. sum (y_pred==y_test) /len (y_test)

In [579]:
import sklearn
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y_test, ans)
print(accuracy)

0.95


In [582]:
Test=np.matrix([1.0,6.3	,3.4,5.6,2.4])
y_p=(sigmoid(np.dot(Test,w))>=0.5).astype(int)
y_p

matrix([[1]])